# Generated by Django 4.0 on 2022-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('attachment', models.FileField(upload_to=None)),
                ('pickup_loc', models.CharField(max_length=50)),
            ],
        ),
    ]
