# Generated by Django 4.0 on 2022-10-04 15:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0002_alter_item_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pickup_loc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wraeclast', 'Wraeclast'), ('lioneyes', "Lioneye's Watch"), ('crimson', 'Crimson Temple'), ('strand', 'Strand'), ('mesa', 'Mesa')], max_length=38),
        ),
    ]
