# Generated by Django 4.0 on 2022-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0002_alter_item_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pickup_loc',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
