# Generated by Django 4.0 on 2022-10-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0003_alter_item_pickup_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pickup_loc_mc',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pickup_loc',
            field=models.CharField(max_length=50),
        ),
    ]
