# Generated by Django 4.0 on 2022-10-04 15:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0003_alter_item_pickup_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pickup_loc_mc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wraeclast', 'Wraeclast'), ('lioneyes', "Lioneye's Watch"), ('crimson', 'Crimson Temple'), ('strand', 'Strand'), ('mesa', 'Mesa')], default='Wraeclast', max_length=38),
        ),
        migrations.AlterField(
            model_name='item',
            name='pickup_loc',
            field=models.CharField(max_length=50),
        ),
    ]
