# Generated by Django 4.0 on 2022-10-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0004_item_pickup_loc_mc_alter_item_pickup_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pickup_loc',
        ),
    ]
