# Generated by Django 4.0 on 2022-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0006_alter_item_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_loc_fs',
            field=models.CharField(choices=[('wraeclast', 'Wraeclast'), ('lioneyes', "Lioneye's Watch"), ('crimson', 'Crimson Temple'), ('strand', 'Strand'), ('mesa', 'Mesa')], default='Wraeclast', max_length=20),
        ),
    ]
