# Generated by Django 4.0 on 2022-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0007_choices_item_pickup_loc_fs'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choice',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='pickup_loc_fs',
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_loc_fs',
            field=models.ManyToManyField(to='delivery_form.Choices'),
        ),
    ]
