# Generated by Django 4.0 on 2022-10-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0008_choices_choice_remove_item_pickup_loc_fs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pickup_loc_mc',
        ),
    ]
